dist: trusty
language: java
cache:
  directories:
    - "$HOME/.m2" # Maven dependencies
jdk:
  - oraclejdk8
script:
  - mvn -Dispyb.url=jdbc:mariadb://localhost:3306 -Dispyb.user=root -Dispyb.host=localhost package
  - sonar-scanner
addons:
  mariadb: '10.3'
  sonarcloud:
    organization: "dbdemon"
    token:
      secure: "mU78WQH+0Ayk90ZU4iNRBMjzcUAl7Mo4Y68YNw77quDFZ9PWrEZf3xfE8hQv7FuYLcAdFgeewTatmsl4Nnfu5+ItE3irfRSxndJ9k0nTR0WIPxixrgYuJuRpmCWRtfcwQWmR/aXo9JCdSIPT4iEzRKpoemmsqLBWtbE0YFHMqPpgTYpzkNn/jsIaUx4wbEifC/13u46527aMgHQTGen4qwL7gi5h2R9d1FCJIH9VtbIFXH6d03MdORKhcJ2qmNXOAAx4rg7XOfMuVeCaSWdY7FkJKjtU/L5uR7xCE/+GE6o6zmsoAx6qeLRsoE7pK7wkT5auWhCfZ2ZjtsKB5SGpttu+JNoAPKcMhgU7kenjrdn+MQLI895m/53968pHmD2ITX6q/jfoAZB8HLKgGKhH1USFTnjwI7CXrP79xlyjpp7+tltzE+XNYztq5KWmgKT6Re6pOkCXu8IBAsOFwSGvyHJssKZfnUcKRBLHRrfMMxB5jGs/mQl4PHBmt177gsEXqPkLCP6l1QF9jrMrEE9rXWrkkVtvhpZU8/vwYMzdhsQvE1jWY7gbpInhpuG/oBaAHD7am2OYnado4vCtx4AfPe2oVVwFpoNw8iurPBHj93kgno/r211dLCTNdiCpTiq7cNSk8wsIXg4uVsrA/QsDZkeCUtA5W0iNx27D+LTnX18="
deploy:
  provider: releases
  api_key:
    secure: xCYbMcMHSBcaqoSC7+rnMCD0eoQOW05VDAz8ctW0H5MujR+buEHlrIRduBDRiRokJUVaPyspur1y+4V4b9H2+YNutQ/5svxLxtgSq0XD3r58ZE++67jcUMOAK39Xgm8hddzRy+VKhMOZ4mX9IxYz/dMwY4+WaVFZ0i57ktvjSLgLrLPTvKSNYhjT7H1G0OBdPzi8K6KVMabn8/p1wTWtWzvTc6rsevy6M8pBuv/u07fHvRhdSDDIw56ScEV5YPQ6XVFLifT9yYwJYmoXPqCnzM1fvA4uOWtmH7ApDZm4CAurFHZFLRwvCrtXfXj+zAWIWMasfNgtuDZFPQoeEtJZKh2DyqKNwMF+xjclji0jGCC7QFA/M8ozAsszUixJvgLvxu871/HVjZnKXbgCrTW6tCs/YFT3NcZgRT9YPpsNuh7XutVjI9G77i9+DPzEQ63K1dfNXUkqtSIpg2Rhdpib7FPgUrhpc2AJPhQpf3b4Ev/Tsc9ItWUcw6jwqbmXYMyeW8cyzA3oVUEW+mZtUkMrWUqIN/tiUTOqvV4QkdVRusqbd1eNp6yrYNOiNlGQCGMYTlxWV8JW2vwzDCj1B4Eef3LDyN0eYhAxTF0jV23wcbj/fWHkpcCjjOPxsLPDiHwYs5vIPsoa0f5/L9rtJEHU282pFcQQTiZXxICJwalVFYM=
  file_glob: true
  file:
    - "target/ispyb-api-*.jar"
  skip_cleanup: true
  on:
    tags: true
