# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:      # pipeline-level
  MYSQL_ROOT_PASSWORD: mysql_root_pwd

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
  paths:
    exclude:
    - '*.md'
    - LICENSE

resources:
  containers:
  - container: mariadb
    image: mariadb:10.5
    env:
      MYSQL_DATABASE: ispybtest
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
    ports:
    - 3306:3306

pool:
  vmImage: ubuntu-20.04

stages:
- stage: build
  displayName: Build
  dependsOn:
  jobs:
  - job: build
    displayName: build package
    pool:
      vmImage: ubuntu-20.04
    services:
      db: mariadb
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        options: '-Dispyb.url="jdbc:mariadb://127.0.0.1:3306" -Dispyb.user=root -Dispyb.pw="$(MYSQL_ROOT_PASSWORD)" -Dispyb.host=127.0.0.1'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
