variables:
  MYSQL_ROOT_PASSWORD: mysql_root_pwd
  MYSQL_HOST: '127.0.0.1'
  MYSQL_PORT: '3306'
  System.Debug: true

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
  paths:
    exclude:
    - '*.md'
    - LICENSE

resources:
  containers:
  - container: mariadb
    image: mariadb:10.6
    env:
      MYSQL_DATABASE: ispybtest
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
    ports:
    - $(MYSQL_PORT):$(MYSQL_PORT)

pool:
  vmImage: ubuntu-20.04

stages:
- stage: build
  displayName: Build
  dependsOn:

  jobs:
  - job: build
    displayName: build package
    pool:
      vmImage: ubuntu-20.04
    services:
      db: mariadb

    steps:
    - task: Maven@3
      displayName: ‘Maven package build’
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: true
        options: '-Dispyb.url="jdbc:mariadb://$(MYSQL_HOST):$(MYSQL_PORT)" -Dispyb.user=root -Dispyb.pw="$(MYSQL_ROOT_PASSWORD)" -Dispyb.host=$(MYSQL_HOST)'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/target
        artifactName: jars
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: jars
    - task: GithubRelease@0
      displayName: ‘Create GitHub Release’
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
      inputs:
        githubConnection: gda-ispyb-api
        repositoryName: DiamondLightSource/gda-ispyb-api
        assets: '$(Pipeline.Workspace)/ispyb-api-*.jar'
